# Generated by Django 4.2.4 on 2023-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_cart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم حامل البطاقة')),
                ('number', models.PositiveBigIntegerField(verbose_name='رقم البطاقة')),
                ('type', models.CharField(choices=[('mastercard', 'mastercard'), ('visa', 'Visa'), ('mada', 'مدى')], max_length=100, verbose_name='نوع البطاقة')),
                ('expiration_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('CVV', models.DecimalField(decimal_places=0, max_digits=4, max_length=4, verbose_name='(CVV) رمز التحقق')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
