# Generated by Django 4.2.4 on 2023-08-04 13:19

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_card_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=month.models.MonthField(verbose_name='تاريخ الانتهاء'),
        ),
    ]
