# Generated by Django 4.2.4 on 2023-08-05 15:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='اسم الدولة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[A-Za-zأ-ي]+\\s[A-Za-zأ-ي]+$'), 'أدخل اسمًا صالحًا يحتوي على كلمتين على الأقل (بدون رموز أو أرقام).')], verbose_name='اسم حامل البطاقة'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=20, max_length=20, verbose_name='رقم البطاقة'),
        ),
    ]
