# Generated by Django 4.2.4 on 2023-08-05 16:00

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_card_country_alter_card_name_alter_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=month.models.MonthField(error_messages={'invalid': 'صيغة التاريخ غير صحيحة.'}, verbose_name='تاريخ الانتهاء'),
        ),
    ]
