# Generated by Django 4.2.4 on 2023-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=20, max_length=20, verbose_name='رقم البطاقة'),
        ),
    ]
